## 00.PyTorch Fundamentals
https://www.learnpytorch.io/00_pytorch_fundamentals


In [ ]:
print("Hello!")

Hello!


In [ ]:
!nvidia-smi

Thu Aug 28 08:25:32 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   54C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


## Introduction to tensors
## Creating tensor


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# find out 有多少dimension
scalar.ndim

0

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])


### Random tensors

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.3192, 0.4218, 0.0920, 0.9488],
        [0.0857, 0.8779, 0.2744, 0.5641],
        [0.5336, 0.3111, 0.7552, 0.3290]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
random_image_size_tensor.ndim

3

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range and tensors like

In [ ]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten = torch.arange(0, 10) # Note: this may return an error in the future
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0])

## Tensor datatypes
### ⚠️ PyTorch 常見錯誤：三大張量問題

> 在使用 PyTorch 和進行深度學習時，最常遇到的錯誤之一，就是「張量不對」，而這些錯誤大致可分為三種情況：

---

#### 1. ❌ Tensors not right datatype（資料型別錯誤）

- 張量的 `dtype` 不對，例如需要 `float32`，但你傳入的是 `int64`。
- 常見錯誤：使用 `CrossEntropyLoss()` 損失函數時，預測值應為 `float32`，但標籤 (label) 需為 `int64`。
- ✅ **解法**：
  ```python
  labels = labels.to(torch.int64)
  inputs = inputs.to(torch.float32)
  ```

#### 2. ❌ Tensors not right shape（張量形狀不對）
- 模型或運算需要特定形狀的張量，但你給的 shape 不正確。
- 常見錯誤訊息:

  ```
  RuntimeError: mat1 and mat2 shapes cannot be multiplied
  ```

- ✅ 解法：檢查並使用 .shape 或 .view()、.reshape()、.permute() 進行調整：

  ```python
  print(tensor.shape)
  tensor = tensor.view(batch_size, -1)  # 攤平成2D輸入

  ```
#### 3. ❌ Tensors not on the right device（裝置錯誤）

- 模型在 GPU 上 (cuda)，但資料在 CPU 上，或反之。

- 常見錯誤訊息：

  ```
  RuntimeError: Expected all tensors to be on the same device, but found at least two devices
  ```
- ✅ 解法：統一將張量與模型放在同一個裝置：

  ```python
  device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
inputs = inputs.to(device)

  ```

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,   # 預設是 None，表示會自動推斷型別，通常是 torch.float32
                               device="cuda",  # 預設是 None，表示放在 CPU 上（除非有特別設定）
                               requires_grad=False) # 是否需要自動微分追蹤

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cuda', index=0))

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

## Getting information from tensors (tensor attributes)

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0699, 0.3818, 0.5524, 0.0230],
        [0.9618, 0.0384, 0.4179, 0.6268],
        [0.5208, 0.3527, 0.8264, 0.8246]])

In [ ]:
# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape} or {some_tensor.size()}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0699, 0.3818, 0.5524, 0.0230],
        [0.9618, 0.0384, 0.4179, 0.6268],
        [0.5208, 0.3527, 0.8264, 0.8246]])
Shape of tensor: torch.Size([3, 4]) or torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (tensor operations)
These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication






In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 100


tensor([101, 102, 103])

In [ ]:
# Multiply tensor by ten
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out Pytorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)



You can do matrix multiplication by hand but it's not recommended.

The in-built torch.matmul() method is faster.


In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 0 ns, sys: 678 µs, total: 678 µs
Wall time: 540 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 66 µs, sys: 15 µs, total: 81 µs
Wall time: 60.8 µs


tensor(14)

## One of the most common errors in deep learning (shape errors)

In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Sum: {x.sum()}")


Minimum: 0
Maximum: 90
Sum: 450


In [ ]:
# mean function don't work on int64(long)
# print(f"Mean: {x.mean()}") # this will error
torch.mean(x.type(torch.float32)) # won't work without float datatype


tensor(45.)

In [ ]:
x.type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype

Mean: 45.0


In [ ]:
 # Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
# Find the position in tensor that has minimum value with argmin()
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## Reshaping, stacking, squeezing and unsqueezing

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

### Reshaping

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
x[0] = 0
z

tensor([[0., 2., 3., 4., 5., 6., 7.]])

In [ ]:
x[0] = 1
# Changing z changes x
z[:, 0] = 5 # 把張量 z 中 第 0 欄（第一欄） 的所有列（row），都改成數值 5
# ↑   ↑
# |   └→ 第 0 欄
# └→ 所有列（用 : 表示）
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

### Stacking

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
x_stacked2 = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked2

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

### Squeezing


> 把 shape 裡面是 1 的維度移除掉（例如 [1, 3, 1, 5] → [3, 5]），讓資料更精簡、便於後續處理。



In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


### Unsqueezing


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


### Permute


> permute(*dims)：傳入一個新的維度順序，把 tensor 的 shape 重排。



In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
test1 = torch.rand(size=(2, 3, 4))
test1_permuted = test1.permute(2, 0, 1)
test1, test1_permuted

(tensor([[[0.3894, 0.1105, 0.4423, 0.7860],
          [0.9506, 0.7536, 0.9258, 0.6243],
          [0.9434, 0.0745, 0.8455, 0.1472]],
 
         [[0.7908, 0.2949, 0.8421, 0.6938],
          [0.8607, 0.3468, 0.5904, 0.8374],
          [0.5196, 0.8259, 0.4686, 0.0571]]]),
 tensor([[[0.3894, 0.9506, 0.9434],
          [0.7908, 0.8607, 0.5196]],
 
         [[0.1105, 0.7536, 0.0745],
          [0.2949, 0.3468, 0.8259]],
 
         [[0.4423, 0.9258, 0.8455],
          [0.8421, 0.5904, 0.4686]],
 
         [[0.7860, 0.6243, 0.1472],
          [0.6938, 0.8374, 0.0571]]]))

## Indexing (selecting data from tensors)

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

* `python torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
* `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.


In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
 array.dtype

dtype('float64')

In [ ]:
# torch的default dtype是float32
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# 所以:
tensor = torch.from_numpy(array).type(torch.float32)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))



> # 如果 tensor 有 `requires_grad=True`，你不能直接 `.numpy()`，你必須先用 `.detach()` 移除梯度資訊才能轉換




In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)


Reproducibility（再現性 或 可重現性）是機器學習與科學研究中的一個重要概念，意思是：
> 🔁「在相同的條件下，別人（或你自己）能夠得到和你一樣的實驗結果。」



In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.0302, 0.3934, 0.2637, 0.8150],
        [0.6936, 0.1029, 0.3818, 0.2975],
        [0.9710, 0.8246, 0.0369, 0.3838]])

Tensor B:
tensor([[0.3977, 0.6424, 0.5937, 0.7329],
        [0.4197, 0.4954, 0.9300, 0.7663],
        [0.7211, 0.2893, 0.1790, 0.0359]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

### Set the random seed


> 每次你要「產生同樣的亂數結果」，就必須 重新把亂數種子設回去原本的值，因為亂數產生器的狀態在用過之後會改變



In [ ]:
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
print(f"Tensor C:\n{random_tensor_C}\n")

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
# torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## 1. Getting a GPU


## 2. Getting PyTorch to run on the GPU

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
# 如果GPU可用就用GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device) # cuda:0 是gpu的index 如果有多個gpu就會有不只有0
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

## Moving tensors back to the CPU\


> 如果想用numpy 要切回cpu才能做


In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
# tensor_on_gpu.numpy()



```
---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

/tmp/ipython-input-704146591.py in <cell line: 0>()
      1 # If tensor is on GPU, can't transform it to NumPy (this will error)
----> 2 tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```



In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises

In [ ]:
# Create a random tensor with shape
tensor1 = torch.rand(7, 7)
tensor1

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])

In [ ]:
tensor2 = torch.rand(1, 7)
print(tensor2)
tensor1 * tensor2.T

tensor([[0.9998, 0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782]])


tensor([[0.1587, 0.6540, 0.3277, 0.6531, 0.3958, 0.9145, 0.2036],
        [0.1200, 0.1199, 0.5645, 0.3963, 0.5832, 0.0519, 0.0024],
        [0.0712, 0.1070, 0.4595, 0.4441, 0.5988, 0.1581, 0.1041],
        [0.0258, 0.0100, 0.0270, 0.0128, 0.0265, 0.0038, 0.0083],
        [0.1120, 0.1039, 0.0639, 0.1370, 0.1441, 0.0236, 0.0400],
        [0.3195, 0.1105, 0.1077, 0.0054, 0.0713, 0.2084, 0.1448],
        [0.0792, 0.2959, 0.0916, 0.0438, 0.1299, 0.0361, 0.1050]])

# 6. Putting it all together

In [1]:
import torch
from torch import nn
import matplotlib.pyplot as plt

# Check out Pytorch version
torch.__version__

'2.8.0+cu126'